### ISSUE TITLE
giving a bunch of false positives, is that normal?

### ISSUE THREAD

**Issue by bunbunzz** [Ramen-Roxy-AJ/jamcrcker#2]
hi, i wanted to try this out since i heard it was a remade version of another cracker, and i wanted to attempt cracking one of my accounts to try it out. i put my actual password and then a bunch of other similar and gibberish passwords in the txt file, but when i ran the cracker it basically marked them all as a found password. is that normal, or did i do something wrong?

**Comment by Ramen-Roxy-AJ** [comment]
That's odd. Could you give me a screenshot so I know what it says? ^^

**Comment by bunbunzz** [comment]
> 
> 
> That's odd. Could you give me a screenshot so I know what it says? ^^

im trying to recreate it but currently golang is being a total ass and saying theres no main.go file as i had to uninstall everything to do something, but basically when i run the code it says "password found! (user:pass)" about 8 times and puts it in the cracks folder. if goland decides to work i can add an image

**Comment by Ramen-Roxy-AJ** [comment]
I think it does need proxies. Don't worry, to find proxies you can search up some proxy generators online and save them as a .txt file. It should probably work with a proxy. Since AJ said they "patched" proxyless cracking.

**Comment by bunbunzz** [comment]
> 
> 
> I think it does need proxies. Don't worry, to find proxies you can search up some proxy generators online and save them as a .txt file. It should probably work with a proxy. Since AJ said they "patched" proxyless cracking.

gotcha, ill go ahead and try that out and let you know if it works ^^

**Comment by Ramen-Roxy-AJ** [comment]
https://user-images.githubusercontent.com/76233667/102826611-a530c100-43a6-11eb-8795-6fc1330ff813.png That image you posted is actually a good sign, it shows that it's actually sending the POST request to AJ's login servers, but it seems that AJ's login servers aren't responding. I'll look more into this.

**Comment by bunbunzz** [comment]
> https://user-images.githubusercontent.com/76233667/102826611-a530c100-43a6-11eb-8795-6fc1330ff813.png That image you posted is actually a good sign, it shows that it's actually sending the POST request to AJ's login servers, but it seems that AJ's login servers aren't responding. I'll look more into this.

gotcha gotcha, should i just close the ticket then?

**Comment by Ramen-Roxy-AJ** [comment]
if you want to! ^^

**Comment by bunbunzz** [comment]
> 
> 
> if you want to! ^^

gotcha, ill be doing that then!
